<?php

return [
    'number_of_user' => 5,
    'admin' => 0,
    'partner' => 1,
    'customer'=> 2,
    'active' => 0,
    'rate_partner' => 0,
    'type_hotel' => 'hotel',
    'type_room' => 'room',
    'number_of_hotel' => 5,
    'pending' => 'Pending',
    'approved' => 'Approved',
    'denied' => 'Denied',
    'approved_number' => 0,
    'denied_number' => 1,
    'pending_number' => 2,
    'vn' => 'vn',
    'en' => 'en',
    'paid' => 'Paid',
    'unpaid' => 'Unpaid',
    'paid_number' => 3,
    'unpaid_number' => 4,
    'paginate_order' => 5,
    'number_of_slide' => 7,
];
