<?php

namespace Tests\Unit\Http\Controllers;

use App\Jobs\SendEmailJob;
use App\Mail\MailNotifyOrder;
use Illuminate\Support\Facades\Mail;
use Tests\TestCase;

class SendEmailJobTest extends TestCase
{
    protected $sendEmailJob;
    protected $data = [
        'name' => 'hoangtrung',
        'revenues' => 500,
        'orders' => 20,
    ];
    protected $mail = 'hoangtrunga1k55@gmail.com';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->sendEmailJob = new SendEmailJob(
            $this->data,
            $this->mail
        );
    }

    public function testHandle()
    {
        Mail::fake();
        $this->sendEmailJob->handle();
        $email = $this->mail;
        Mail::assertSent(MailNotifyOrder::class, function ($mail) use ($email) {
            return $mail->hasTo($email);
        });
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
